[package]
name = "tgrade-valset"
version = "0.5.2"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Control the validator set based on membership of trusted tg4 contract"
repository = "https://github.com/confio/tgrade-contracts"
homepage = "https://tgrade.finance"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "artifacts/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw-utils = { version = "0.11.0" }
cw2 = { version = "0.11.0" }
tg4 = { path = "../../packages/tg4", version = "0.5.2" }
tg-bindings = { version = "0.5.2", path = "../../packages/bindings" }
tg-utils = { version = "0.5.2", path = "../../packages/utils" }
cw-controllers = { version = "0.11.0" }
cw-storage-plus = { version = "0.11.0" }
cosmwasm-std = { version = "1.0.0-beta" }
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta" }
cw-multi-test = "0.11.0"
tg4-engagement = { path = "../tg4-engagement", version = "0.5.2" }
tg4-stake = { path = "../tg4-stake", version = "0.5.2" }
# we enable multitest feature only for tests
tg-bindings-test = { path = "../../packages/bindings-test", version = "0.5.2" }
derivative = "2"
anyhow = "1"
assert_matches = "1.5"
