[package]
name = "tg4-engagement"
version = "0.5.2"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Simple TG4 implementation of group membership controlled by an admin"
repository = "https://github.com/confio/tgrade-contracts"
homepage = "https://tgrade.finance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw-utils = "0.11.0"
cw2 = "0.11.0"
cw-controllers = "0.11.0"
cw-storage-plus = "0.11.0"
tg4 = { path = "../../packages/tg4", version = "0.5.2" }
tg-utils = { version = "0.5.2", path = "../../packages/utils" }
tg-bindings = { version = "0.5.2", path = "../../packages/bindings" }
cosmwasm-std = { version = "1.0.0-beta" }
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta" }
cw-multi-test = { version = "0.11.0" }
tg-bindings-test = { version = "0.5.2", path = "../../packages/bindings-test" }
tg4-mixer = { path = "../tg4-mixer/", version = "0.5.2" }
derivative = "2"
anyhow = "1"
