[package]
name = "tg-test-utils"
version = "0.5.2"
authors = ["Jakub Bogucki <jakub@confio.gmbh>"]
edition = "2018"
description = "Utilities used in contract tests"
repository = "https://github.com/confio/tgrade-contracts"
homepage = "https://tgrade.finance"

[dependencies]
cosmwasm-std = "1.0.0-beta"
tg-voting-contract = { path = "../voting-contract", version = "0.5.2" }
